# Generated by Django 3.2.5 on 2021-08-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateTimeField()),
                ('location', models.CharField(max_length=64)),
                ('offered_salary', models.IntegerField()),
                ('Qualification', models.IntegerField()),
            ],
        ),
    ]
