# Generated by Django 3.2.5 on 2021-08-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_jobmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('published_date', models.DateField()),
            ],
        ),
    ]
