# Generated by Django 3.2.5 on 2021-08-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('c_no', models.IntegerField()),
                ('mail_id', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
